// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/rossifedericoe/go-dependecy-injection/app"
	"github.com/rossifedericoe/go-dependecy-injection/app/controllers"
	"github.com/rossifedericoe/go-dependecy-injection/app/services"
)

// Injectors from wire.go:

func InitializeApp() app.App {
	bikeService := services.NewBikeService()
	homeController := controllers.NewBikeController(bikeService)
	carService := services.NewCarService()
	carController := controllers.NewCarController(carService)
	appApp := app.NewApp(homeController, carController)
	return appApp
}
